GaragePlanner/Controllers/AdminController.cs
using Domain;
using Domain.utils;
using GaragePlanner.Models;
using Microsoft.AspNetCore.Mvc;

namespace GaragePlanner.Controllers
{
    public class AdminController : Controller
    {
        private readonly CarCollection _carCollection;
        public AdminController(CarCollection collection)
        {
            _carCollection = collection;
        }

        [HttpGet]
        public IActionResult Index(AdminViewModel model)
        {
            try
            {
                model.Brands = _carCollection.GetAllCurrentBrands();
                return View(model);
            }
            catch (DalException ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }
            catch (Exception ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }
        }

        

        [HttpPost]
        public IActionResult AddBrand(string AddBrandName)
        {
            try
            {
                if (!_carCollection.TryAddBrand(AddBrandName))
                {
                    ErrorViewModel errorViewModel = new()
                    {
                        ErrorMessage = "This brand is already existent in the system."
                    };
                    return View("Error", errorViewModel);
                }

                AdminViewModel model = new()
                {
                    AddBrandName = AddBrandName
                };
                return View("Confirmation", model);
            }
            catch (DalException ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }
            catch (Exception ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }
        }

        [HttpPost]
        public IActionResult DeleteBrand(string DeleteBrandName)
        {
            try
            {
                if (!_carCollection.TryDeleteBrand(DeleteBrandName))
                {
                    ErrorViewModel errorViewModel = new()
                    {
                        ErrorMessage = "This brand is not existent in the system."
                    };
                    return View("Error", errorViewModel);
                }

                AdminViewModel model = new()
                {
                    DeleteBrandName = DeleteBrandName
                };

                return View("Confirmation", model);
            }
            catch (DalException ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }
            catch (Exception ex)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };
                Console.WriteLine(ex);
                return View("Error", errorViewModel);
            }

        }
    }
}

GaragePlanner/Controllers/AgendaController.cs
using Core;
using Domain;
using Domain.interfaces;
using GaragePlanner.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using DAL;
using Domain.dto;
using Domain.utils;
using System;

namespace GaragePlanner.Controllers
{
    public class AgendaController : Controller
    {
        private readonly AppointmentCollection _appointmentCollection;


        public AgendaController(AppointmentCollection collection)
        {
            _appointmentCollection = collection;
        }

        public IActionResult Index()
        {
            try
            {
                _appointmentCollection.LoadAgenda();

                AgendaViewModel model = new();

                IReadOnlyList<Day> days = _appointmentCollection.Days;

                foreach (var day in days)
                {
                    DayViewModel dayViewModel = new() { Date = day.DateOfDay };
                    foreach (TimeSlot timeslot in day.TimeSlots)
                    {
                        TimeSlotViewModel timeslotViewModel = new()
                        {
                            Time = timeslot.StartTime,
                            IsAvailable = timeslot.IsAvailable(),
                        };
                        dayViewModel.TimeSlots.Add(timeslotViewModel);
                    }

                    model.Days.Add(dayViewModel);
                }

                return View(model);
            }
            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }

        }



    }
}

GaragePlanner/Controllers/CarController.cs
using Core;
using DAL;
using Domain;
using Domain.dto;
using Domain.interfaces;
using GaragePlanner.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using Domain.utils;

namespace GaragePlanner.Controllers
{
    public class CarController : Controller
    {

        private readonly CustomerCollection _customerCollection;
        private readonly CarCollection _carCollection;


        public CarController(CustomerCollection customerCollection, CarCollection carCollection)
        {
            _carCollection = carCollection;
            _customerCollection = customerCollection;

        }

        [HttpGet]
        public ActionResult Index(AddCarViewModel carViewModel)
        {
            try
            {
                carViewModel.Brands = _carCollection.GetAllCurrentBrands();
                


                carViewModel.CustomerEmails = _customerCollection.GetCustomerEmails();
            }
            catch (DalException)
            {
                ErrorViewModel errorViewModel = new()
                {
                    ErrorMessage = "Something went wrong, please try again"
                };
                return View("Error", errorViewModel);
            }


            return View(carViewModel);
        }

        [HttpPost]

        public ActionResult AddCar(AddCarViewModel addCarViewModel)
        {

            try
            {
                string email = addCarViewModel.SelectedCustomerEmail;
                string brand = addCarViewModel.SelectedBrand;
                if (!_carCollection.TryCreateCar(email, addCarViewModel.LicensePlate, brand,
                        addCarViewModel.SelectedColor, addCarViewModel.Year))
                {
                    ErrorViewModel errorViewModel = new()
                    {
                        ErrorMessage = "License plate already exist. Contact support if this should not be the case."
                    };
                    return View("Error", errorViewModel);
                };
            }
            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }


            return RedirectToAction("Index", "Home");
        }

        public ActionResult DeleteCar(int id)
        {
            try
            {
                _carCollection.DeleteCar(id);

            }
            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult EditCar(OverviewCarViewModel model)
        {
            model.Brands = _carCollection.GetAllCurrentBrands();
            Car car = new (
                model.Id,
                model.LicensePlate,
                model.Color,
                model.SelectedBrand,
                model.Year
                );
            try
            {
                _carCollection.EditCar(car);
            }
            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }


            return RedirectToAction("Overview");
        }

        public ActionResult Overview(OverviewCarViewModel model)
        {
            try
            {
                model.CustomerEmails = _customerCollection.GetCustomerEmails();
                model.Brands = _carCollection.GetAllCurrentBrands();
                List<Car> customerCars = _carCollection.GetCustomerCarsByCustomerEmail("fefefefefefefe@gmail.com");
                model.Cars = customerCars;
            }
            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }

            return View(model);
        }



    }
}

GaragePlanner/Controllers/RegistrationController.cs
using Core;
using DAL;
using Domain.interfaces;
using Domain.utils;
using GaragePlanner.Models;
using Microsoft.AspNetCore.Mvc;




namespace GaragePlanner.Controllers

{
    public class RegistrationController : Controller
    {
        private readonly CustomerCollection _customerCollection;
        public RegistrationController(CustomerCollection customerCollection )
        {
            _customerCollection = customerCollection;
        }   

        public IActionResult Index()
        {
            return View();
        }

 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterCustomer(RegistrationViewModel registrationViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(registrationViewModel);
            }

            try
            {

                _customerCollection.TryCreateCustomer(
                    registrationViewModel.FirstName,
                    registrationViewModel.LastName,
                    registrationViewModel.Address,
                    registrationViewModel.Email,
                    registrationViewModel.Password
                );
            }

            catch (DalException exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Technical issues, please try again later."
                };

                return View("Error", errorViewModel);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                var errorViewModel = new ErrorViewModel()
                {
                    ErrorMessage = "Something went wrong, please contact support"
                };

                return View("Error", errorViewModel);
            }

            return RedirectToAction("RegistrationSuccess", registrationViewModel);
        }

        public IActionResult RegistrationSuccess(RegistrationViewModel model)
        {
            return View(model);
        }
    }

}

GaragePlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Planner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GaragePlanner.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Garage Planner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarShowAgendaViewModelupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Registration</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="carDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Car
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="carDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Car" asp-action="Overview">Overview</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Car" asp-action="Index">Add Car</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="Index">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GaragePlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>